spring.application.name=backend

# PostgreSQL Database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/pulsecart}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Charan@2006}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true